name: vercel 배포

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: 상위 디렉토리로 이동 후 ./wanna-woowa-blog/ 디렉토리 재귀적으로 복사
        run: sh ./build.sh
      - name: lurgi 개인 레포로 푸시
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.LURGI_PRIVATE_ACCESS_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: lurgi
          destination-repository-name: wanna-woowa-blog
          user-email: wahoo9040@naver.com
          commit-message: "build to vercel"
          target-branch: main
      - name: 클론 경로를 echo
        run: echo $DESTINATION_CLONED_DIRECTORY
